@Booth.DockerVolumeBackup.WebApi_HostAddress = http://localhost:5239
@scheduleId=1
@backupId=1


GET {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/schedules

###

GET {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/schedules/{{scheduleId}}

###

POST {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/schedules
Content-Type: application/json

{
    "Name": "",
    "Enabled": true,
    "Days": { "Sunday": true, "Monday": false, "Tuesday": false, "Wednesday": false, "Thursday": false, "Friday": false, "Saturday": false },
    "Time": "15:30:00",
    "Volumes": [ "Volume1", "Volume2" ]
}
###

PUT {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/schedules/{{scheduleId}}
Content-Type: application/json

{ 
    //ScheduleDto
}
###

DELETE {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/schedules/{{scheduleId}}

###


GET {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/backups

###

GET {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/backups?scheduleId={{scheduleId
}}

###

GET {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/backups/{{backupId}}

###

GET {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/backups/{{backupId}}/log

###

POST {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/backups/{{backupId}}/run

###

POST {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/backups/run
Content-Type: application/json

{
  //VolumeBackupRequestDto
}

###

GET {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/backups/{{id}}/status

###

GET {{Booth.DockerVolumeBackup.WebApi_HostAddress}}/api/volumes

###
